### ISSUE TITLE
Create the non-funtional Account page

### ISSUE THREAD

**Issue by alvaldes** [Sesame-Disk/cool-storage-microfrontend#27]
Objective: Create account page to show users info

Story points: 2

**Comment by abelguzman** [comment]
hey @alvaldes is not clear to me how this issue is different from https://github.com/Sesame-Disk/cool-storage-microfrontend/issues/23 please add details on both issues about what the difference is between the two. So it's clearer, if you think is not required to have those, then please try explain to me so I get the diffs.

**Comment by alvaldes** [comment]
I didn't realize it was already created
